'use strict';
(() => {
const T={
'منو':'Menu','رویدادها':'Events','مجله':'Journal','کارت هدیه':'Gift Card','پنل من':'My Account','سبد':'Cart','سبد خرید':'Shopping Cart','جمع':'Total','ادامه و تسویه':'Continue to Checkout','سبد خرید خالی است.':'Your cart is empty.','تجربه دیجیتال کافه':'Digital café experience','رزرو':'Reservation','QR Menu':'QR Menu',
'قهوه‌ای که':'Coffee worth','بهانه‌ی برگشتن می‌شود.':'coming back for.','یک تجربه کامل دیجیتال برای انتخاب، سفارش، رزرو و کشف طعم‌های تازه؛ از میز کافه تا سفارش بیرون‌بر.':'A complete digital experience for choosing, ordering, reserving, and discovering new flavors—from your café table to takeaway.','سفارش از منو':'Order from Menu','رزرو میز':'Reserve a Table','☕ دانه تخصصی':'☕ Specialty beans','⚡ سفارش سریع':'⚡ Fast ordering','🎁 امتیاز وفاداری':'🎁 Loyalty points','محبوب‌های امروز':"Today's Favorites",'میانگین رضایت':'Average rating','عضو باشگاه':'Club members','۱۸ ساعت':'18 hours','عصاره‌گیری Cold Brew':'Cold Brew extraction','هر روز':'Every day','دانه تازه':'Fresh beans','میزت را خودت انتخاب کن':'Choose your own table','تاریخ':'Date','ساعت':'Time','تعداد نفر':'Guests','فضا':'Area','سالن اصلی':'Main hall','کنار پنجره':'By the window','تراس':'Terrace','انتخاب موقعیت میز':'Choose table location','ثبت رزرو':'Confirm Reservation','🎟 رویدادهای کافه':'🎟 Café Events','ورکشاپ دم‌آوری، شب موسیقی آکوستیک و Coffee Tasting.':'Brewing workshops, acoustic music nights, and coffee tastings.','مشاهده رویدادها':'View Events','🎁 کارت هدیه':'🎁 Gift Card','یک تجربه خوش‌طعم را برای دوستت هدیه کن.':'Gift a delicious café experience to someone special.','ساخت Gift Card':'Create Gift Card','📖 مجله قهوه':'📖 Coffee Journal','داستان دانه‌ها، روش‌های دم‌آوری و راهنمای انتخاب.':'Bean stories, brewing methods, and coffee guides.','مطالعه Blog':'Read the Blog',
'ورود / ثبت‌نام':'Sign In / Register','نام و نام خانوادگی':'Full name','ایمیل':'Email','موبایل':'Mobile','رمز عبور':'Password','قوانین باشگاه مشتریان را می‌پذیرم':'I accept the loyalty club terms','ورود / ساخت حساب':'Sign In / Create Account',
'مجله Ashkan Café':'Ashkan Café Journal','راهنمای انتخاب قهوه بر اساس ذائقه':'How to Choose Coffee for Your Taste','از شکلاتی و آجیلی تا میوه‌ای و گلی؛ چطور انتخاب کنیم؟':'From chocolatey and nutty to fruity and floral—how do you choose?','۵ دقیقه مطالعه':'5 min read','Cold Brew چیست؟':'What Is Cold Brew?','چرا عصاره‌گیری سرد طعمی نرم‌تر و متفاوت می‌سازد.':'Why cold extraction creates a smoother, distinct flavor.','۴ دقیقه مطالعه':'4 min read','V60 در خانه':'V60 at Home','یک دستور ساده و تکرارپذیر برای شروع دم‌آوری.':'A simple, repeatable recipe to start brewing at home.','۷ دقیقه مطالعه':'7 min read',
'تسویه حساب چندمرحله‌ای':'Multi-Step Checkout','۱. تحویل':'1. Delivery','۲. پرداخت':'2. Payment','۳. تأیید':'3. Confirmation','نوع سفارش':'Order type','دریافت حضوری':'Pickup','ارسال':'Delivery','نام':'Name','کد تخفیف':'Coupon code','آدرس':'Address','مرحله پرداخت':'Continue to Payment','روش پرداخت':'Payment Method','💳 کارت بانکی':'💳 Bank Card','💵 پرداخت در کافه':'💵 Pay at Café','🎁 Gift Card':'🎁 Gift Card','ثبت سفارش':'Place Order','✓ سفارش ثبت شد':'✓ Order Placed','سفارش شما با موفقیت دریافت شد و در پنل کاربری قابل پیگیری است.':'Your order was received successfully and can be tracked from your account.','پیگیری سفارش':'Track Order','تخفیف:':'Discount:',
'پنل مشتری':'Customer Dashboard','مهمان':'Guest','پروفایل':'Profile','امتیاز باشگاه':'Loyalty Points','سفارش':'Orders','تاریخچه سفارش‌ها':'Order History','رزروهای من':'My Reservations','باشگاه مشتریان':'Loyalty Club','هر خرید امتیاز دارد؛ با رسیدن به سطوح بالاتر، تخفیف و نوشیدنی هدیه دریافت می‌کنی.':'Every purchase earns points. Reach higher tiers to unlock discounts and complimentary drinks.','۳۲۰ از ۱۰۰۰ امتیاز تا سطح بعدی':'320 of 1,000 points to the next tier','هنوز سفارشی ثبت نشده.':'No orders yet.','رزروی ندارید.':'No reservations yet.','تأیید شده':'Confirmed','در حال آماده‌سازی':'Preparing','میز':'Table',
'رویدادها و تجربه‌ها':'Events & Experiences','جمعه ۱۸:۰۰':'Friday · 18:00','شناخت اسیدیته، بادی و نت‌های عطری سه دانه منتخب.':'Explore acidity, body, and aroma notes across three selected beans.','ثبت‌نام':'Register','پنجشنبه ۲۰:۳۰':'Thursday · 20:30','شب موسیقی آکوستیک':'Acoustic Music Night','یک شب آرام با موسیقی زنده و منوی ویژه.':'A relaxed evening with live music and a special menu.','رزرو صندلی':'Reserve a Seat','شنبه ۱۶:۰۰':'Saturday · 16:00','ورکشاپ V60':'V60 Workshop','نسبت قهوه به آب، Grind Size و تکنیک Pour Over.':'Coffee-to-water ratio, grind size, and pour-over technique.','شرکت می‌کنم':"I'm In",
'کارت هدیه دیجیتال':'Digital Gift Card','برای یک دوست خاص':'For Someone Special','۵۰۰٬۰۰۰ تومان':'500,000 Toman','یک فنجان حال خوب مهمان من ☕':'A cup of happiness is on me ☕','نام گیرنده':'Recipient name','مبلغ':'Amount','۵۰۰ هزار تومان':'500,000 Toman','۱ میلیون تومان':'1,000,000 Toman','۲ میلیون تومان':'2,000,000 Toman','پیام':'Message','ساخت کارت هدیه':'Create Gift Card','برای ':'For ','یک دوست خاص':'Someone Special',
'نظر مشتریان':'Customer Reviews','سارا':'Sara','کیفیت قهوه عالی و بالانس طعم خیلی خوب بود.':'Excellent coffee quality and a beautifully balanced flavor.','آرمان':'Arman','بسته‌بندی و آماده‌سازی سریع.':'Fast preparation and great packaging.','ثبت Review':'Write a Review','امتیاز':'Rating','نظر':'Review','ثبت نظر':'Submit Review','افزودن به سبد':'Add to Cart','جزئیات':'Details','این QR را روی میز یا استند چاپ کن تا مشتری مستقیماً منوی دیجیتال را باز کند.':'Print this QR on a table card or stand so guests can open the digital menu instantly.',
'اسپرسو اسپشیالتی':'Specialty Espresso','لاته کارامل':'Caramel Latte','کولد برو':'Cold Brew','آیس موکا':'Iced Mocha','چیزکیک قهوه':'Coffee Cheesecake','کروسان بادام':'Almond Croissant','دبل شات با دانه ۱۰۰٪ عربیکا، رُست متوسط':'Double shot with 100% Arabica beans and a medium roast','اسپرسو، شیر بافت‌دار و کارامل دست‌ساز':'Espresso, textured milk, and house-made caramel','عصاره‌گیری سرد ۱۸ ساعته، نرم و شفاف':'18-hour cold extraction with a smooth, clean finish','شکلات تلخ، اسپرسو و شیر سرد':'Dark chocolate, espresso, and chilled milk','چیزکیک خامه‌ای با عطر قهوه':'Creamy cheesecake with an aromatic coffee note','کروسان کره‌ای با کرم بادام':'Buttery croissant filled with almond cream',
'لطفاً یک میز انتخاب کنید':'Please choose a table.','رزرو با موفقیت ثبت شد':'Reservation confirmed successfully.','به سبد خرید اضافه شد':'Added to cart.','سبد خرید خالی است':'Your cart is empty.','نظر شما ثبت شد':'Your review was submitted.','ثبت‌نام آزمایشی انجام شد':'Demo registration completed.','صندلی شما رزرو شد':'Your seat has been reserved.','به لیست شرکت‌کنندگان اضافه شدی':'You were added to the attendee list.','Gift Card ساخته شد':'Gift Card created.'
};
const REVERSE=Object.fromEntries(Object.entries(T).map(([fa,en])=>[en,fa]));
const A={'فضای کافه و قهوه تخصصی':'Café interior and specialty coffee','QR منوی کافه':'Café menu QR code'};
// Stage 10: event-driven localization. No MutationObserver and no reload loops.
const originals=new WeakMap();
function savedLanguage(){try{return localStorage.getItem('lang')==='fa'?'fa':'en'}catch{return 'en'}}
// Cache original text nodes once: language switching does not rescan the full DOM.
let staticNodes=[];
function indexStaticNodes(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;staticNodes=[];while((n=walker.nextNode())){const parent=n.parentElement;if(!parent||['SCRIPT','STYLE','NOSCRIPT','TEXTAREA'].includes(parent.tagName))continue;originals.set(n,n.nodeValue);staticNodes.push(n);}}
function translateText(s){const trim=s.trim();if(!trim)return s;let out=T[trim];if(!out){const m=trim.match(/^میز (\d+)$/);if(m)out='Table '+m[1];else if(trim.startsWith('تخفیف:'))out=trim.replace('تخفیف:','Discount:');else return s;}return s.replace(trim,out);}
function apply(root=document){
 const lang=savedLanguage();const en=lang==='en';
 document.documentElement.lang=lang;document.documentElement.dir=en?'ltr':'rtl';document.body?.classList.toggle('en',en);
 const scope=root.nodeType===9?root.body:root;if(!scope)return;
 const nodes=scope===document.body?staticNodes:(()=>{const a=[];const w=document.createTreeWalker(scope,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))a.push(n);return a})();
 for(const node of nodes){if(!node.isConnected)continue;
  const parent=node.parentElement;if(!parent||['SCRIPT','STYLE','NOSCRIPT','TEXTAREA'].includes(parent.tagName))continue;
  if(!originals.has(node))originals.set(node,node.nodeValue);
  const original=originals.get(node);const desired=en?translateText(original):(REVERSE[original.trim()]?original.replace(original.trim(),REVERSE[original.trim()]):original);
  if(node.nodeValue!==desired)node.nodeValue=desired;
 }
 scope.querySelectorAll?.('[alt]').forEach(el=>{if(!el.dataset.originalAlt)el.dataset.originalAlt=el.alt;el.alt=en?(A[el.dataset.originalAlt]||el.dataset.originalAlt):el.dataset.originalAlt});
 const btn=document.getElementById('langBtn');if(btn){btn.textContent=en?'فارسی':'English';btn.setAttribute('aria-label',en?'Switch to Persian':'تغییر زبان به انگلیسی');}
}
function setLanguage(lang){if(!['fa','en'].includes(lang))return;try{localStorage.setItem('lang',lang)}catch{}apply();
 try{if(typeof renderProducts==='function')renderProducts();if(typeof renderCart==='function')renderCart();}catch(e){console.warn('Localized product refresh failed',e)}
 document.dispatchEvent(new CustomEvent('cafe:languagechange',{detail:{lang}}));
}
window.cafeI18n={apply,setLanguage,refresh(root=document){if(root===document){indexStaticNodes();apply()}else apply(root)},t:T};
document.addEventListener('DOMContentLoaded',()=>{
 try{if(!['fa','en'].includes(localStorage.getItem('lang')))localStorage.setItem('lang','en')}catch{}
 indexStaticNodes();apply();const btn=document.getElementById('langBtn');if(btn)btn.addEventListener('click',()=>setLanguage(document.documentElement.lang==='en'?'fa':'en'));
 document.addEventListener('cafe:contentupdated',e=>{const root=e.detail?.root||document;window.cafeI18n.refresh(root)});
});
})();
