'use strict';
(()=>{
 const fa=()=>localStorage.getItem('lang')==='fa';
 const dictionary={favorites:['Favorites','علاقه‌مندی‌ها'],empty:['No favorites yet. Tap a heart on a product.','هنوز محصول محبوبی ندارید. روی قلب محصولات بزنید.'],all:['All products','همه محصولات'],reduce:['Reduce motion','کاهش حرکت'],motion:['Enable motion','فعال‌کردن حرکت']};
 const label=k=>dictionary[k][fa()?1:0];
 const read=()=>{try{return JSON.parse(localStorage.getItem('ac_favorites')||'[]')}catch{return []}};
 const save=a=>localStorage.setItem('ac_favorites',JSON.stringify(a));
 function decorate(){document.querySelectorAll('#products .card').forEach((card,i)=>{if(card.querySelector('.favorite-toggle'))return;const id=Number(card.querySelector('[onclick^="addCart"]')?.getAttribute('onclick')?.match(/\d+/)?.[0]);if(!id)return;const b=document.createElement('button');b.type='button';b.className='favorite-toggle';b.dataset.id=id;b.setAttribute('aria-label',fa()?'تغییر علاقه‌مندی':'Toggle favorite');b.onclick=()=>{const s=new Set(read());s.has(id)?s.delete(id):s.add(id);save([...s]);refresh()};card.append(b)});refresh()}
 function refresh(){const s=new Set(read());document.querySelectorAll('.favorite-toggle').forEach(b=>{const active=s.has(Number(b.dataset.id));b.textContent=active?'♥':'♡';b.setAttribute('aria-pressed',String(active))});const count=document.getElementById('favoritesCount');if(count)count.textContent=s.size}
 function controls(){const menu=document.querySelector('.menu-tools');if(menu&&!document.querySelector('#favoritesFilter')){const b=document.createElement('button');b.id='favoritesFilter';b.className='category-btn';b.type='button';b.innerHTML=`♡ ${label('favorites')} <span id="favoritesCount">0</span>`;menu.querySelector('.menu-categories')?.append(b);b.addEventListener('click',()=>{const on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.classList.toggle('active',on);document.querySelectorAll('#products .card').forEach(card=>{const id=Number(card.querySelector('.favorite-toggle')?.dataset.id);card.hidden=on&&!read().includes(id)});});refresh()}}
 function tilt(){const hero=document.querySelector('.hero-grid > img');if(!hero)return;hero.classList.add('stage5-tilt');const media=matchMedia('(prefers-reduced-motion: reduce)');const host=hero.parentElement;host.addEventListener('pointermove',e=>{if(media.matches||e.pointerType==='touch')return;const r=host.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;hero.style.transform=`perspective(1100px) rotateY(${x*9}deg) rotateX(${-y*7}deg) translateY(-5px)`});host.addEventListener('pointerleave',()=>hero.style.transform='')}
 function reservation(){const map=document.getElementById('tableMap');if(!map)return;const date=document.getElementById('rdate');if(date){const now=new Date();date.min=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`}map.querySelectorAll('.table-seat').forEach((b,i)=>{b.type='button';b.setAttribute('aria-label',fa()?`میز ${i+1}`:`Table ${i+1}`);b.setAttribute('aria-pressed',String(b.classList.contains('selected')));b.addEventListener('click',()=>queueMicrotask(()=>map.querySelectorAll('.table-seat').forEach(x=>x.setAttribute('aria-pressed',String(x.classList.contains('selected'))))))})}
 document.addEventListener('DOMContentLoaded',()=>{controls();decorate();tilt();reservation();const box=document.querySelector('#products');if(box)new MutationObserver(()=>{decorate();if(document.querySelector('#favoritesFilter[aria-pressed="true"]'))document.querySelectorAll('#products .card').forEach(card=>{const id=Number(card.querySelector('.favorite-toggle')?.dataset.id);card.hidden=!read().includes(id)})}).observe(box,{childList:true});});
})();
