const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const products=[
{id:1,n:'اسپرسو اسپشیالتی',en:'Specialty Espresso',p:89000,img:'images/hot.jpeg',cat:'coffee',d:'دبل شات با دانه ۱۰۰٪ عربیکا، رُست متوسط',de:'Double shot with 100% Arabica beans and a medium roast',rate:4.9},
{id:2,n:'لاته کارامل',en:'Caramel Latte',p:135000,img:'images/menu.jpg',cat:'coffee',d:'اسپرسو، شیر بافت‌دار و کارامل دست‌ساز',de:'Espresso, textured milk, and house-made caramel',rate:4.8},
{id:3,n:'کولد برو',en:'Cold Brew',p:128000,img:'images/menu2.jpg',cat:'cold',d:'عصاره‌گیری سرد ۱۸ ساعته، نرم و شفاف',de:'18-hour cold extraction with a smooth, clean finish',rate:4.7},
{id:4,n:'آیس موکا',en:'Iced Mocha',p:145000,img:'images/menu3.jpg',cat:'cold',d:'شکلات تلخ، اسپرسو و شیر سرد',de:'Dark chocolate, espresso, and chilled milk',rate:4.8},
{id:5,n:'چیزکیک قهوه',en:'Coffee Cheesecake',p:168000,img:'images/delight.jpg',cat:'dessert',d:'چیزکیک خامه‌ای با عطر قهوه',de:'Creamy cheesecake with an aromatic coffee note',rate:4.9},
{id:6,n:'کروسان بادام',en:'Almond Croissant',p:149000,img:'images/delighttwo.jpg',cat:'dessert',d:'کروسان کره‌ای با کرم بادام',de:'Buttery croissant filled with almond cream',rate:4.6}
];
const money=n=>new Intl.NumberFormat(document.body.classList.contains('en')?'en-US':'fa-IR').format(n)+(document.body.classList.contains('en')?' Toman':' تومان');
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)); const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function toast(t){let e=$('#toast');if(!e){e=document.createElement('div');e.id='toast';e.className='toast';document.body.append(e)}e.textContent=t;e.style.display='block';setTimeout(()=>e.style.display='none',2200)}
function renderProducts(){const box=$('#products');if(!box)return;box.innerHTML=products.map(x=>`<article class="card"><a href="product.html?id=${x.id}"><img loading="lazy" src="${x.img}" alt="${x.n}"></a><div class="card-body"><div class="row between"><span class="badge">★ ${x.rate}</span><span class="price">${money(x.p)}</span></div><h3>${document.body.classList.contains('en')?x.en:x.n}</h3><p class="muted">${document.body.classList.contains('en')?x.de:x.d}</p><div class="row"><a class="btn alt" href="product.html?id=${x.id}">${document.body.classList.contains('en')?'Details':'جزئیات'}</a><button class="btn" onclick="addCart(${x.id})">${document.body.classList.contains('en')?'Add to cart':'افزودن به سبد'}</button></div></div></article>`).join('')}
function addCart(id){let c=get('ac_cart',[]),i=c.find(x=>x.id===id);i?i.q++:c.push({id,q:1});set('ac_cart',c);renderCart();toast('به سبد خرید اضافه شد')}
function renderCart(){let c=get('ac_cart',[]),b=$('#cartItems'),count=$('#cartCount');if(count)count.textContent=c.reduce((a,x)=>a+x.q,0);if(!b)return;let total=0;b.innerHTML=c.map(x=>{let p=products.find(z=>z.id===x.id);total+=p.p*x.q;return `<div class="cart-item"><img src="${p.img}"><div><b>${document.body.classList.contains('en')?p.en:p.n}</b><div class="muted">${money(p.p)} × ${x.q}</div><div class="row"><button class="iconbtn" onclick="qty(${x.id},1)">+</button><button class="iconbtn" onclick="qty(${x.id},-1)">−</button></div></div><button class="iconbtn" onclick="removeCart(${x.id})">×</button></div>`}).join('')||'<p class="muted">سبد خرید خالی است.</p>';let t=$('#cartTotal');if(t)t.textContent=money(total)}
function qty(id,d){let c=get('ac_cart',[]),i=c.find(x=>x.id===id);if(i)i.q+=d;c=c.filter(x=>x.q>0);set('ac_cart',c);renderCart()} function removeCart(id){set('ac_cart',get('ac_cart',[]).filter(x=>x.id!==id));renderCart()}
function initShell(){document.body.insertAdjacentHTML('afterbegin',`<header class="top"><div class="container nav"><a class="brand" href="index.html">Ashkan Café</a><nav class="navlinks"><a href="index.html#menu">منو</a><a href="events.html">رویدادها</a><a href="blog.html">مجله</a><a href="gift-card.html">کارت هدیه</a><a href="dashboard.html">پنل من</a></nav><div class="actions"><button class="iconbtn" id="langBtn">FA/EN</button><button class="iconbtn" id="themeBtn">◐</button><a class="iconbtn" href="auth.html">♙</a><button class="btn" id="cartBtn">سبد <span id="cartCount">0</span></button></div></div></header><aside id="cartDrawer" class="drawer"><div class="row between"><h2>سبد خرید</h2><button class="iconbtn" id="closeCart">×</button></div><div id="cartItems"></div><div class="row between"><b>جمع</b><b id="cartTotal"></b></div><a class="btn" style="width:100%;margin-top:16px" href="checkout.html">ادامه و تسویه</a></aside>`);document.body.insertAdjacentHTML('beforeend',`<div id="toast" class="toast"></div><footer class="footer"><div class="container row between"><b>Ashkan Café</b><span class="muted">© 2026 — تجربه دیجیتال کافه</span><div class="row"><a href="qr-menu.html">QR Menu</a><a href="index.html#reserve">رزرو</a></div></div></footer>`);$('#cartBtn').onclick=()=>$('#cartDrawer').classList.add('open');$('#closeCart').onclick=()=>$('#cartDrawer').classList.remove('open');$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');$('#langBtn').onclick=()=>{document.body.classList.toggle('en');localStorage.lang=document.body.classList.contains('en')?'en':'fa';renderProducts()};if(localStorage.lang==='en')document.body.classList.add('en');renderCart()}
document.addEventListener('DOMContentLoaded',()=>{initShell();renderProducts();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});
